# F12
version: "2"

services:

  web:
    build: .
    image: ctftraining/base_image_nginx_mysql_php_73
    restart: always
    ports:
      - "0.0.0.0:8300:80"
    environment:
      - FLAG=flag{y0u_4re_mas7er_1n_v1ew_sourc4}
